FROM mcr.microsoft.com/dotnet/aspnet
ENV ASPNETCORE_URLS=http://+:80
ADD tsetab.ir.pem /usr/local/share/ca-certificates/tsetab.ir.crt
RUN chmod 644 /usr/local/share/ca-certificates/tsetab.ir.crt && update-ca-certificates
copy . App/
WORKDIR /App
ENTRYPOINT ["dotnet", "IFS.Red.WebApi.dll"]
