
IF OBJECT_ID(N'dbo.SLE0101', N'U') IS NULL
BEGIN

CREATE TABLE Sle0101(
	[Id] [bigint] NOT NULL,
	[CIdGrc] [nvarchar](2) NULL,
	[CEtaGrc] [nvarchar](1) NULL,
	[DSeaBs] [nvarchar](8) NULL,
	[HSeaBs] [nvarchar](6) NULL,
	[DHEmisMsgSpi] [nvarchar](14) NULL,
	[IClGrc] [nvarchar](1) NULL,
 CONSTRAINT [PK_Sle0101] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

END


if NOT EXISTS (SELECT *  FROM sys.indexes  WHERE name='IX_Sle0101_CIdGrc' 
    AND object_id = OBJECT_ID('[dbo].[Sle0101]'))
begin
	CREATE NONCLUSTERED INDEX [IX_Sle0101_CIdGrc] ON [dbo].[Sle0101]
	(
		[CIdGrc] ASC
	)
	INCLUDE([CEtaGrc],[DSeaBs]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
end


if NOT EXISTS (SELECT *  FROM sys.indexes  WHERE name='IX_Sle0101_CIdGrc_DSeaBs' 
    AND object_id = OBJECT_ID('[dbo].[Sle0101]'))
begin
	CREATE NONCLUSTERED INDEX [IX_Sle0101_CIdGrc_DSeaBs] ON [dbo].[Sle0101]
	(
		[CIdGrc] ASC,
		[DSeaBs] DESC
	)
	INCLUDE([CEtaGrc]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
end
