IF OBJECT_ID(N'dbo.SLE0106', N'U') IS NULL
BEGIN

CREATE TABLE Sle0106(
	[Id] [bigint] NOT NULL,
	[DSeaBs] [nvarchar](8) NULL,
	[HSeaBs] [nvarchar](6) NULL,
	[CValISIN] [nvarchar](12) NULL,
	[CEtaVal] [nvarchar](2) NULL,
	[CActModEtaVal] [nvarchar](1) NULL,
	[HOvPgmVal] [nvarchar](6) NULL,
	[DHEmisMsgSpi] [nvarchar](14) NULL,
 CONSTRAINT [PK_Sle0106] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] 



END


if NOT EXISTS (SELECT *  FROM sys.indexes  WHERE name='IX_Sle0106_CValISIN' 
    AND object_id = OBJECT_ID('[dbo].[Sle0106]'))
begin
	CREATE NONCLUSTERED INDEX [IX_Sle0106_CValISIN] ON [dbo].[Sle0106]
	(
		[CValISIN] ASC
	)
	INCLUDE([DSeaBs],[CEtaVal]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
end


if NOT EXISTS (SELECT *  FROM sys.indexes  WHERE name='IX_Sle0106_CValISIN_DSeaBs' 
    AND object_id = OBJECT_ID('[dbo].[Sle0106]'))
begin
	CREATE NONCLUSTERED INDEX [IX_Sle0106_CValISIN_DSeaBs] ON [dbo].[Sle0106]
	(
		[CValISIN] ASC,
		[DSeaBs] DESC
	)
	INCLUDE([HSeaBs],[CEtaVal]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
end



